"""empty message

Revision ID: 50877f1c9e77
Revises: 
Create Date: 2020-07-17 22:32:26.138120

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '50877f1c9e77'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('ventas',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('productos', sa.Text(), nullable=False),
    sa.Column('id_producto', sa.Integer(), nullable=False),
    sa.Column('total_venta', sa.Integer(), nullable=False),
    sa.Column('id_usuario', sa.Integer(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('ventas')
    # ### end Alembic commands ###
