"""empty message

Revision ID: 5b4941f4b8f9
Revises: 9fb5ab049366
Create Date: 2020-07-22 14:01:15.036531

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '5b4941f4b8f9'
down_revision = '9fb5ab049366'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('venta_producto', sa.Column('id_producto', sa.Integer(), nullable=False))
    op.drop_column('venta_producto', 'id_producto_pk')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('venta_producto', sa.Column('id_producto_pk', sa.INTEGER(), autoincrement=False, nullable=False))
    op.drop_column('venta_producto', 'id_producto')
    # ### end Alembic commands ###
