"""empty message

Revision ID: 8eb48cbe0546
Revises: 5b4941f4b8f9
Create Date: 2020-07-22 14:15:49.616529

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '8eb48cbe0546'
down_revision = '5b4941f4b8f9'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('ventas',
    sa.Column('id_venta', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('id_usuario', sa.Integer(), nullable=False),
    sa.Column('fecha', sa.DATE(), nullable=False),
    sa.PrimaryKeyConstraint('id_venta')
    )
    op.create_foreign_key(None, 'venta_producto', 'ventas', ['id_venta_pk'], ['id_venta'])
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'venta_producto', type_='foreignkey')
    op.drop_table('ventas')
    # ### end Alembic commands ###
