"""empty message

Revision ID: 9fb5ab049366
Revises: 
Create Date: 2020-07-22 13:28:45.327870

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '9fb5ab049366'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('producto',
    sa.Column('id_producto', sa.Integer(), nullable=False),
    sa.Column('nombre_producto', sa.Text(), nullable=False),
    sa.Column('precio', sa.Integer(), nullable=False),
    sa.PrimaryKeyConstraint('id_producto')
    )
    op.create_table('ventas',
    sa.Column('id_venta', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('id_usuario', sa.Integer(), nullable=False),
    sa.Column('fecha', sa.Date(), nullable=False),
    sa.PrimaryKeyConstraint('id_venta')
    )
    op.create_table('venta_producto',
    sa.Column('id_venta_pk', sa.Integer(), nullable=False),
    sa.Column('id_producto_pk', sa.Integer(), nullable=False),
    sa.Column('cantidad', sa.Integer(), nullable=False),
    sa.Column('precio', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['id_producto_pk'], ['producto.id_producto'], ),
    sa.ForeignKeyConstraint(['id_venta_pk'], ['ventas.id_venta'], ),
    sa.PrimaryKeyConstraint('id_venta_pk', 'id_producto_pk')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('venta_producto')
    op.drop_table('ventas')
    op.drop_table('producto')
    # ### end Alembic commands ###
